#!/usr/bin/env bash
# This script installs nginx on web-01 server
# This script uses a 301 redirection to nyancat
# https://www.youtube.com/watch?v=B0lD6y-R6yc&list=WL&index=85

find="^\tlocation / {"
replace301="\tlocation /redirect_me {\n\t\treturn 301 \@scheme://www.youtube.com/watch?v=B0lD6y-R6yc&list=WL&index=85;\n\t}\n\n\tlocation / {"

sudo apt-get -y update
sudo apt-get install -y nginx
sudo rm /var/www/html/*.html
sudo echo "Hello World" | sudo tee /var/www/html/index.html
sudo sed -i "s|$find|$replace301|" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
